### ISSUE TITLE
Sort is case-sensitive

### ISSUE THREAD

**Issue by reinerblock** [hieuthi/joplin-plugin-markdown-table-sortable#1]
There is no option if the sorting shall be case-sensitive or not. It always sorts case-sensitive. Therefore, at first, there are values in capital letters and afterwards values starting with lower case. :( 

As long as there is no option for it, is it possible to set “case-insensitive” as default? 'Cause my guess is that is what most prefer.

Suggesting greetings
Reiner

**Comment by hieuthi** [comment]
Version [1.1.0](https://github.com/hieuthi/joplin-plugin-markdown-table-sortable/releases/tag/v1.1.0) and later will be case-insensitive.
