### ISSUE TITLE
probably localised date issue

### ISSUE THREAD

**Issue by EmVee381** [hieuthi/joplin-plugin-markdown-table-sortable#2]
i found that sorting by date doesnt work in localised version of date...i am just reporting it it is not real issue for me but i guess it should be corrected.

![image](https://user-images.githubusercontent.com/63140027/148510349-09f63270-eeb3-4b6b-b929-4e7000c919e5.png)

**Comment by hieuthi** [comment]
It is not the date it's trailing time that is the problem. The library does not support datetime format, only date. It require quite a lot of works to support this as the library will need to be significantly rewritten and there are many datetime format, so I will not support it.

For people who have similar problem, I will recommend using ISO 8601 datetime format (e.g., `2022-01-07T10:44:12`) if you want to use both date and time and make sure they are sorted correctly

**Comment by EmVee381** [comment]
ok undertand that.. yes i noted it just because i use shortcut in joplin for inserting date, and it is filled in localised format.... thank you or reply and sugestions, it could help someone in future...

**Comment by hieuthi** [comment]
For inserting datetime, you can use my other plugin [Slash Commands](https://github.com/hieuthi/joplin-plugin-slash-commands) which makes it easy to add different type of datetime format (include iso date) simply by typing `/now`.
