### ISSUE TITLE
Apply Sorting not visible

### ISSUE THREAD

**Issue by JackGruber** [hieuthi/joplin-plugin-markdown-table-sortable#4]
When the table ist the first element, the `Apply Sorting` is not visible, since it is outside of the editor

![grafik](https://user-images.githubusercontent.com/24863925/165995431-8114979a-65fe-436e-bd81-6062a930b278.png)

![grafik](https://user-images.githubusercontent.com/24863925/165995259-d71f6e8f-c1b2-40b6-8b52-9af9bdc17117.png)

**Comment by hieuthi** [comment]
Thanks for reporting, I added a simple fixes that will work most of the time in v1.2.2. There are some edge cases that are still remaining, but most users will not see it.
