### ISSUE TITLE
Plugin no longer works starting with Joplin 3.0.3

### ISSUE THREAD

**Issue by JackGruber** [hieuthi/joplin-plugin-markdown-table-sortable#5]
Renderd md has no longer `source-line` and `source-line-end` for tables
https://github.com/laurent22/joplin/issues/10466

**Comment by hieuthi** [comment]
Version 3.0.3 is pre-release, let observe this problem for a while before start fixing it.

**Comment by JackGruber** [comment]
It should be fixed in Joplin, not in the Plugin. This issue was only as information.

**Comment by JackGruber** [comment]
Fixed in Joplin `3.0.9`
